"""Even Fibonacci numbers
   Show HTML problem content
   Problem 2
   Each new term in the Fibonacci sequence is generated by adding the previous
   two terms. By starting with 1 and 2, the first 10 terms will be:
   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
   By considering the terms in the Fibonacci sequence whose values
   do not exceed four million, find the sum of the even-valued terms.
"""


array = {}


def fib(num_):
    array[num_] = array.get(num_, 0) \
                  or (num_ <= 1 and 1 or fib(num_ - 1) + fib(num_ - 2))
    return array[num_]


n = 0
i = 0
while fib(i) <= 4000000:
    if not fib(i) % 2:
        n = n + fib(i)
    i += 1

print(n)
